export enum LogType {
    GuildJoined = 'GuildJoined',
    GuildLeft = 'GuildLeft',
    ChannelAdded = 'ChannelAdded',
    ChannelRemoved = 'ChannelRemoved',
    PlayerJoined = 'PlayerJoined',
    PlayerStriked = 'PlayerStriked',
    PlayerBanned = 'PlayerBanned',
    SudokuStartedSingle = 'SudokuStartedSingle',
    SudokuStartedVS = 'SudokuStartedVS',
    SudokuStartedRoyale = 'SudokuStartedRoyale',
    SudokuSolvedSingle = 'SudokuSolvedSingle',
    SudokuSolvedVS = 'SudokuSolvedVS',
    SudokuSolvedRoyale = 'SudokuSolvedRoyale',
    SudokuStoppedSingle = 'SudokuStoppedSingle',
}